import Foundation
import UIKit

struct PDFReportService {
    static func createViolationReport(
        violation: ViolationRecord,
        community: Community?,
        property: Property?,
        images: [UIImage]
    ) -> URL? {
        let bounds = CGRect(x: 0, y: 0, width: 612, height: 792)
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = [
            kCGPDFContextCreator as String: "HOA Drive-By",
            kCGPDFContextAuthor as String: "HOA Drive-By",
            kCGPDFContextTitle as String: "Violation Report"
        ]
        let renderer = UIGraphicsPDFRenderer(bounds: bounds, format: format)
        let outputURL = FileManager.appDocumentsDirectory.appendingPathComponent("Violation-\(violation.id.uuidString.prefix(8)).pdf")

        do {
            try renderer.writePDF(to: outputURL) { context in
                context.beginPage()
                var y: CGFloat = 40

                func draw(_ text: String, font: UIFont, spacing: CGFloat = 8) {
                    let rect = CGRect(x: 40, y: y, width: 532, height: 1000)
                    let attributes: [NSAttributedString.Key: Any] = [.font: font]
                    let attributed = NSAttributedString(string: text, attributes: attributes)
                    let size = attributed.boundingRect(
                        with: CGSize(width: 532, height: 1000),
                        options: [.usesLineFragmentOrigin, .usesFontLeading],
                        context: nil
                    )
                    attributed.draw(with: CGRect(x: 40, y: y, width: 532, height: ceil(size.height) + 6),
                                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                                    context: nil)
                    y += ceil(size.height) + spacing
                }

                draw("Violation Report", font: .boldSystemFont(ofSize: 24), spacing: 16)
                draw("Community: \(community?.name ?? "Unknown")", font: .systemFont(ofSize: 13))
                draw("Property: \(property?.displayName ?? "Unknown")", font: .systemFont(ofSize: 13))
                draw("Category: \(violation.category.rawValue)", font: .systemFont(ofSize: 13))
                draw("Status: \(violation.status.rawValue)", font: .systemFont(ofSize: 13))
                draw("Created: \(violation.createdAt.shortDateTime)", font: .systemFont(ofSize: 13))
                draw("Updated: \(violation.updatedAt.shortDateTime)", font: .systemFont(ofSize: 13))
                draw("GPS: \(violation.coordinateText)", font: .systemFont(ofSize: 13))
                draw("Title: \(violation.title)", font: .systemFont(ofSize: 13))
                draw("Notes:", font: .boldSystemFont(ofSize: 14), spacing: 4)
                draw(violation.note.isEmpty ? "No notes entered." : violation.note, font: .systemFont(ofSize: 13), spacing: 14)

                for image in images.prefix(2) {
                    if y > 540 {
                        context.beginPage()
                        y = 40
                    }
                    let rect = CGRect(x: 40, y: y, width: 250, height: 180)
                    image.draw(in: rect)
                    y += 190
                }

                if y < 740 {
                    draw("Generated by HOA Drive-By", font: .systemFont(ofSize: 11))
                }
            }
            return outputURL
        } catch {
            print("PDF creation error: \(error)")
            return nil
        }
    }
}
